### PR TITLE
Add localStorage for last succesfull city

### LINKED ISSUE #5: Keep last search in local storage
Save the last searched city in the local storage (unless the city was not found).

### PR DESCRIPTION
**Pull request by AlithAnar**
I've added a bit error handling to the weather request to check if the response is succesful, before saving the weather to the localStorage.

Fixes #5

### CODE REVIEW

**Comment by jordihm9** [comment]
Nice! I have a couple of questions/suggestions:
1. Is there a reason to replace `,` to `;` at the end of each property of the types declared? (just to know, I'm curious)
2. I guess you finally want to save the result from the API instead of the city searched, so the app will be faster and prevent sending multiple requests. But I think it's not the best solution in this case since the app has to show to the user the updated forecast.
Imagine I search London today at 14.21 and it tells me it's currently raining. If tomorrow I want to check the forecast for London aswell and it's not raining, the app will tell me it's raining because of it saved the last result from the last day.
I have a great solution for this:
1. Save forecast as it currently does.
2. Save the timestamp when the request was sent.
3. When the app is loaded, get the forecast if it's possible and then the timestamp. Then compare the timestamp with the current date and if it passed 30 min ~ 1h (I don't know how much time would be the best) get the city name from the forecast (`currentForecast.name`) and send a request to get the updated forecast.

Please if you have any question or concern about this, let me know!

**Comment by AlithAnar** [comment]
Hi,

1. This is just a result of auto-fixing with Pretties (which I have installed on vscode). Those linting rules are default. Do you want me to disable Prettier linting for your project?
2. I was a bit confused - my first implementation was saving the last searched city name and put it into the search bar. Then I changed it to result storage. When I'm thinking It's totally dumb right now :) I would go to this flow:
- Search for the city forecast
- If successful, store the search phrase in the localStorage
- on app refresh, do the request for the actual forecast using saved search phrase (if exist)
WDYT?

**Comment by jordihm9** [comment]
Hi,
1. Yes please, I prefer to have consistency within all the project, thank you.
2. Yes I think for the moment it's better to save just the phrase and send a request when the page is refreshed. I will work on what I said earlier.

**Comment by AlithAnar** [comment]
@jordihm9 Fixed the storage flow and linter changes

**Review by jordihm9 — APPROVED** [review]

**Pull request merged**
